#!/usr/bin/env python3
"""Render CHANGELOG.md from changelog.json, the changelog XivMcp shows.

changelog.json is the single source of truth: the plugin shows the same entries in game in the What's new tab, and CHANGELOG.md is
generated from it so the two can never disagree.

    tools/changelog.py            write CHANGELOG.md
    tools/changelog.py --check    exit 1 (and print a diff) if it is out of date

Statuses mean the same thing in every one of these mods:

    new   NEW    in a release, seen working in game
    fix   FIX    in a release, seen working in game
    beta  BETA   merged, but not yet verified in game
    next  SOON   still being built

Nothing here needs a toolchain: python3 only, so CI can answer in seconds.
"""

import argparse
import difflib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(ROOT, "changelog.json")
TARGET = os.path.join(ROOT, "CHANGELOG.md")

TAGS = {
    "new": ("NEW", "Added"),
    "fix": ("FIX", "Fixed"),
    "beta": ("BETA", "Merged, not yet verified in game"),
    "next": ("SOON", "Being built"),
}

PREAMBLE = """<!-- Generated from changelog.json by tools/changelog.py. Do not edit this file:
     edit changelog.json and run tools/changelog.py. CI fails when they drift. -->

Statuses mean exactly what they mean in the What's new view in game:

* **NEW** / **FIX** — in a release, seen working in game.
* **BETA** — merged, but not yet verified in game.
* **SOON** — still being built.
"""


def load():
    with open(SOURCE, encoding="utf-8") as fh:
        data = json.load(fh)
    for rel in data["releases"]:
        for key in ("version", "title", "blurb", "items"):
            if key not in rel:
                raise SystemExit("changelog.json: release %r has no %s" % (rel.get("version"), key))
        if not rel["items"]:
            raise SystemExit("changelog.json: release %s has no items" % rel["version"])
        for item in rel["items"]:
            if item.get("status") not in TAGS:
                raise SystemExit(
                    "changelog.json: unknown status %r in %s" % (item.get("status"), rel["version"])
                )
            if not item.get("text"):
                raise SystemExit("changelog.json: an item in %s has no text" % rel["version"])
    return data


def render(data):
    out = ["# Changelog\n\n%s\n\n%s" % (data["intro"].rstrip(), PREAMBLE)]
    for rel in data["releases"]:
        if rel["version"] == "next":
            out.append("\n## [Unreleased] — %s\n" % rel["title"])
        else:
            out.append("\n## [%s] — %s\n" % (rel["version"], rel["title"]))
        out.append("\n%s\n" % rel["blurb"])
        groups = []
        for item in rel["items"]:
            if not groups or groups[-1][0] != item["status"]:
                groups.append((item["status"], []))
            groups[-1][1].append(item["text"])
        single = len({i["status"] for i in rel["items"]}) == 1
        for status, texts in groups:
            if not single:
                out.append("\n### %s\n" % TAGS[status][1])
            out.append("\n")
            for text in texts:
                out.append("* %s\n" % text)
    return "".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail when CHANGELOG.md is out of date")
    args = ap.parse_args()
    wanted = render(load())
    if not args.check:
        with open(TARGET, "w", encoding="utf-8") as fh:
            fh.write(wanted)
        print("wrote %s" % os.path.relpath(TARGET, ROOT))
        return 0
    try:
        with open(TARGET, encoding="utf-8") as fh:
            have = fh.read()
    except FileNotFoundError:
        have = ""
    if have == wanted:
        print("CHANGELOG.md matches changelog.json")
        return 0
    sys.stdout.writelines(
        difflib.unified_diff(
            have.splitlines(True), wanted.splitlines(True),
            "CHANGELOG.md", "changelog.json (rendered)",
        )
    )
    sys.stderr.write("\nCHANGELOG.md is out of date: run tools/changelog.py\n")
    return 1


if __name__ == "__main__":
    sys.exit(main())
