#!/usr/bin/env bash
# Register the in-game XivMcp server with Claude Code: user scope, HTTP transport,
# http://127.0.0.1:<port>/mcp. The bearer token is NOT stored in Claude's config and never printed:
# a headersHelper script reads it from the plugin config each time Claude Code connects.
#
# Usage: tools/claude-mcp-add.sh [--name ffxiv] [--port N] [--dry-run]
#
#   --name     server name in Claude Code (default: ffxiv). An existing user-scope entry is replaced.
#   --port     port (default: Port from the plugin config, else 41800)
#   --dry-run  print what would be registered; change nothing
#
# Environment: XIVMCP_CONFIG  plugin config (default: ~/.xlcore/pluginConfigs/XivMcp.json)
# The helper goes to ${XDG_DATA_HOME:-~/.local/share}/xiv-mcp/headers-helper (mode 700).
set -euo pipefail

name="ffxiv"
port=""
dry_run=0
config="${XIVMCP_CONFIG:-$HOME/.xlcore/pluginConfigs/XivMcp.json}"
helper="${XDG_DATA_HOME:-$HOME/.local/share}/xiv-mcp/headers-helper"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) name="${2:?--name needs a value}"; shift 2 ;;
    --port) port="${2:?--port needs a value}"; shift 2 ;;
    --dry-run) dry_run=1; shift ;;
    -h|--help) sed -n '2,13p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "claude-mcp-add: unknown argument: $1" >&2; exit 2 ;;
  esac
done

[[ "$name" =~ ^[A-Za-z0-9_-]+$ ]] || { echo "claude-mcp-add: bad name: $name" >&2; exit 2; }
command -v python3 >/dev/null 2>&1 || { echo "claude-mcp-add: python3 is required" >&2; exit 1; }

if [[ -z "$port" ]]; then
  port="$(python3 -c 'import json,sys
try: print(int(json.load(open(sys.argv[1], encoding="utf-8-sig")).get("Port", 41800)))
except Exception: print(41800)' "$config")"
fi
if ! [[ "$port" =~ ^[0-9]+$ ]] || (( port < 1 || port > 65535 )); then
  echo "claude-mcp-add: bad port: $port" >&2
  exit 2
fi
url="http://127.0.0.1:$port/mcp"

# Prints {"Authorization":"Bearer <token>"} for Claude Code, or {} when the plugin requires no token.
helper_body="$(cat <<HELPER
#!/usr/bin/env python3
# Generated by xiv-mcp tools/claude-mcp-add.sh: Claude Code headersHelper for the XivMcp plugin.
import json, os, sys
path = os.environ.get("XIVMCP_CONFIG") or "$config"
try:
    with open(path, encoding="utf-8-sig") as f:
        cfg = json.load(f)
except OSError as e:
    sys.exit(f"xiv-mcp headers-helper: cannot read {path}: {e.strerror} (load the XivMcp plugin once)")
except ValueError:
    sys.exit(f"xiv-mcp headers-helper: {path} is not valid JSON")
if not cfg.get("RequireToken", True):
    print("{}")
    sys.exit(0)
token = str(cfg.get("BearerToken") or "").strip()
if not token:
    sys.exit(f"xiv-mcp headers-helper: no BearerToken in {path}")
print(json.dumps({"Authorization": "Bearer " + token}))
HELPER
)"

server_json="$(python3 -c 'import json,sys; print(json.dumps({"type":"http","url":sys.argv[1],"headersHelper":sys.argv[2]}))' "$url" "$helper")"

if [[ "$dry_run" -eq 1 ]]; then
  printf '# %s\n%s\n\n' "$helper" "$helper_body"
  printf "claude mcp add-json --scope user %s '%s'\n" "$name" "$server_json"
  exit 0
fi

command -v claude >/dev/null 2>&1 || { echo "claude-mcp-add: 'claude' (Claude Code CLI) not found on PATH" >&2; exit 1; }
[[ -f "$config" ]] || echo "claude-mcp-add: note: $config does not exist yet; load the plugin in game before connecting." >&2

mkdir -p "$(dirname "$helper")"
( umask 077; printf '%s\n' "$helper_body" > "$helper.tmp" )
chmod 700 "$helper.tmp"
mv -f "$helper.tmp" "$helper"

claude mcp remove --scope user "$name" >/dev/null 2>&1 || true
claude mcp add-json --scope user "$name" "$server_json" >/dev/null
echo "claude-mcp-add: registered '$name' -> $url (user scope, token via $helper). Check: claude mcp get $name" >&2
