#!/usr/bin/env bash
# Register the in-game XivMcp server with Claude Code (user scope, HTTP transport) WITHOUT storing
# the bearer token in Claude's config: a headersHelper script reads BearerToken from the plugin's
# config file each time Claude Code connects.
#
# Usage: tools/claude-mcp-add.sh [--name xiv-mcp] [--url http://127.0.0.1:41800/mcp]
#                                [--scope user] [--config ~/.xlcore/pluginConfigs/XivMcp.json]
#                                [--helper-dir DIR] [--force] [--dry-run]
#
#   --force     replace an existing server registration with the same name
#   --dry-run   write nothing; print the helper and the server JSON that would be registered
#
# The helper is installed to ${XDG_DATA_HOME:-~/.local/share}/xiv-mcp/headers-helper (mode 700).
# It prints {"Authorization":"Bearer <token>"} (or {} when the plugin does not require a token).
# Claude Code runs it at connect/reconnect and after a 401/403. Nothing here prints the token.
set -euo pipefail

name="xiv-mcp"
url="http://127.0.0.1:41800/mcp"
scope="user"
config="${XIVMCP_CONFIG:-$HOME/.xlcore/pluginConfigs/XivMcp.json}"
helper_dir="${XDG_DATA_HOME:-$HOME/.local/share}/xiv-mcp"
force=0
dry_run=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --name) name="$2"; shift 2 ;;
    --url) url="$2"; shift 2 ;;
    --scope) scope="$2"; shift 2 ;;
    --config) config="$2"; shift 2 ;;
    --helper-dir) helper_dir="$2"; shift 2 ;;
    --force) force=1; shift ;;
    --dry-run) dry_run=1; shift ;;
    -h|--help) sed -n '2,17p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "claude-mcp-add: unknown argument: $1" >&2; exit 2 ;;
  esac
done

command -v python3 >/dev/null 2>&1 || { echo "claude-mcp-add: python3 is required (helper and JSON)" >&2; exit 1; }

helper="$helper_dir/headers-helper"

# The helper body. The config path is baked in; XIVMCP_CONFIG overrides it at run time.
read -r -d '' helper_body <<EOF || true
#!/bin/sh
# Generated by xiv-mcp tools/claude-mcp-add.sh. Prints MCP auth headers for Claude Code's headersHelper.
exec python3 - "\${XIVMCP_CONFIG:-$config}" <<'PY'
import json, sys
path = sys.argv[1]
try:
    with open(path, encoding="utf-8-sig") as f:
        cfg = json.load(f)
except FileNotFoundError:
    sys.exit(f"xiv-mcp headers-helper: {path} not found (load the XivMcp plugin once so it creates its config)")
except (OSError, ValueError) as e:
    sys.exit(f"xiv-mcp headers-helper: cannot read {path}: {e}")
if not cfg.get("RequireToken", True):
    print("{}")
    sys.exit(0)
token = cfg.get("BearerToken") or ""
if not token:
    sys.exit(f"xiv-mcp headers-helper: no BearerToken in {path}")
print(json.dumps({"Authorization": "Bearer " + token}))
PY
EOF

server_json="$(python3 -c 'import json,sys; print(json.dumps({"type":"http","url":sys.argv[1],"headersHelper":sys.argv[2]}))' "$url" "$helper")"

if [[ "$dry_run" -eq 1 ]]; then
  echo "# helper -> $helper"
  printf '%s\n' "$helper_body"
  echo "# claude mcp add-json --scope $scope $name '$server_json'"
  exit 0
fi

command -v claude >/dev/null 2>&1 || { echo "claude-mcp-add: 'claude' (Claude Code CLI) not found on PATH" >&2; exit 1; }

mkdir -p "$helper_dir"
umask 077
printf '%s\n' "$helper_body" > "$helper.tmp"
chmod 700 "$helper.tmp"
mv -f "$helper.tmp" "$helper"
echo "claude-mcp-add: installed headers helper at $helper" >&2

if [[ ! -f "$config" ]]; then
  echo "claude-mcp-add: note: $config does not exist yet; load the plugin in game once before connecting." >&2
fi

if claude mcp get "$name" >/dev/null 2>&1; then
  if [[ "$force" -eq 1 ]]; then
    claude mcp remove --scope "$scope" "$name" >&2
  else
    echo "claude-mcp-add: an MCP server named '$name' already exists; re-run with --force to replace it." >&2
    exit 1
  fi
fi

claude mcp add-json --scope "$scope" "$name" "$server_json"
echo "claude-mcp-add: registered '$name' ($url) at $scope scope. Check with: claude mcp get $name" >&2
